"""Add Lead and LeadStage models

Revision ID: 64b9b67b7b2e
Revises: 6099462cb27c
Create Date: 2026-01-06 23:04:09.665282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '64b9b67b7b2e'
down_revision = '6099462cb27c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_stages_id'), 'lead_stages', ['id'], unique=False)
    op.create_index(op.f('ix_lead_stages_name'), 'lead_stages', ['name'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('signing_date', sa.Date(), nullable=True),
    sa.Column('plot_number', sa.String(length=50), nullable=True),
    sa.Column('block_number', sa.String(length=50), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('legal_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('registration_expenses_before_vat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fee_and_registration_before_vat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('registration_expenses_by_summary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fee_by_summary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shared_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('transaction_name', sa.String(length=255), nullable=True),
    sa.Column('id_scan', sa.String(length=500), nullable=True),
    sa.Column('search_component', sa.String(length=255), nullable=True),
    sa.Column('land_component', sa.String(length=255), nullable=True),
    sa.Column('land_component_text', sa.String(length=500), nullable=True),
    sa.Column('search_component_text', sa.String(length=500), nullable=True),
    sa.Column('transaction_amount_text', sa.String(length=500), nullable=True),
    sa.Column('search_component_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('additional_buyer_details', sa.Text(), nullable=True),
    sa.Column('membership_request', sa.String(length=255), nullable=True),
    sa.Column('fee_agreement', sa.String(length=255), nullable=True),
    sa.Column('client_recognition_form', sa.String(length=255), nullable=True),
    sa.Column('signing_status', sa.String(length=100), nullable=True),
    sa.Column('fee_payment_status', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_count', sa.Integer(), nullable=True),
    sa.Column('realization_date', sa.Date(), nullable=True),
    sa.Column('realization_number', sa.String(length=50), nullable=True),
    sa.Column('realization_status', sa.String(length=100), nullable=True),
    sa.Column('has_improvement_levy', sa.Boolean(), nullable=True),
    sa.Column('days_to_report', sa.Integer(), nullable=True),
    sa.Column('days_to_purchase_tax_payment', sa.Integer(), nullable=True),
    sa.Column('report_deadline', sa.Date(), nullable=True),
    sa.Column('purchase_tax_payment_deadline', sa.Date(), nullable=True),
    sa.Column('payment_request_sent_date', sa.Date(), nullable=True),
    sa.Column('days_to_send_payment_request', sa.Integer(), nullable=True),
    sa.Column('payment_request_deadline', sa.Date(), nullable=True),
    sa.Column('date_trigger', sa.String(length=255), nullable=True),
    sa.Column('payment_request_date_trigger', sa.String(length=255), nullable=True),
    sa.Column('payment_request_send_trigger', sa.String(length=255), nullable=True),
    sa.Column('reminder_message3_trigger', sa.String(length=255), nullable=True),
    sa.Column('reminder_message4_trigger', sa.String(length=255), nullable=True),
    sa.Column('reminder_message5_trigger', sa.String(length=255), nullable=True),
    sa.Column('reminder_message6_trigger', sa.String(length=255), nullable=True),
    sa.Column('morning_client_id_company', sa.String(length=100), nullable=True),
    sa.Column('morning_client_id_office', sa.String(length=100), nullable=True),
    sa.Column('invoice_id', sa.String(length=100), nullable=True),
    sa.Column('invoice_source', sa.String(length=255), nullable=True),
    sa.Column('morning_item_id', sa.String(length=100), nullable=True),
    sa.Column('financial_client_created', sa.Boolean(), nullable=True),
    sa.Column('morning_client_created', sa.Boolean(), nullable=True),
    sa.Column('payment_request_document', sa.String(length=500), nullable=True),
    sa.Column('payment_request_link', sa.String(length=500), nullable=True),
    sa.Column('signing_documents_word', sa.String(length=500), nullable=True),
    sa.Column('signing_documents_pdf', sa.String(length=500), nullable=True),
    sa.Column('signed_by_client_documents', sa.String(length=500), nullable=True),
    sa.Column('documents_for_lawyer_verification', sa.String(length=500), nullable=True),
    sa.Column('verified_client_signed_documents', sa.String(length=500), nullable=True),
    sa.Column('attachments_link', sa.String(length=500), nullable=True),
    sa.Column('attachments_and_agreement_link', sa.String(length=500), nullable=True),
    sa.Column('signed_attachments_and_agreement', sa.String(length=500), nullable=True),
    sa.Column('company_seller_documents', sa.String(length=500), nullable=True),
    sa.Column('company_seller_signing_link', sa.String(length=500), nullable=True),
    sa.Column('signed_by_company_seller_documents', sa.String(length=500), nullable=True),
    sa.Column('verified_company_seller_signed_documents', sa.String(length=500), nullable=True),
    sa.Column('lawyer_name', sa.String(length=255), nullable=True),
    sa.Column('lawyer_name_general', sa.String(length=255), nullable=True),
    sa.Column('authorized_signer_for_company', sa.String(length=255), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('client_type', sa.String(length=100), nullable=True),
    sa.Column('is_employee_or_self_employed', sa.Boolean(), nullable=True),
    sa.Column('full_transaction_details', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_sent', sa.Boolean(), nullable=True),
    sa.Column('transfer_to_registration', sa.Boolean(), nullable=True),
    sa.Column('transfer_to_ownership_registration', sa.Boolean(), nullable=True),
    sa.Column('transfer_to_appointments_board', sa.Boolean(), nullable=True),
    sa.Column('group_transactions_after_realization', sa.Boolean(), nullable=True),
    sa.Column('create_levy_board_item', sa.Boolean(), nullable=True),
    sa.Column('create_financial_client_trigger', sa.String(length=255), nullable=True),
    sa.Column('poa_share_agreement', sa.String(length=500), nullable=True),
    sa.Column('poa_planning', sa.String(length=500), nullable=True),
    sa.Column('non_payment_reason', sa.String(length=255), nullable=True),
    sa.Column('coordinated_call_payment_date', sa.Date(), nullable=True),
    sa.Column('initiated_contact_attempts', sa.Integer(), nullable=True),
    sa.Column('last_contact_date', sa.Date(), nullable=True),
    sa.Column('collection_notes', sa.Text(), nullable=True),
    sa.Column('plot_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('realization_completed_if_error', sa.Boolean(), nullable=True),
    sa.Column('reminder_message3_date', sa.Date(), nullable=True),
    sa.Column('reminder_message4_date', sa.Date(), nullable=True),
    sa.Column('reminder_message5_date', sa.Date(), nullable=True),
    sa.Column('reminder_message6_date', sa.Date(), nullable=True),
    sa.Column('check_call_reminder', sa.Date(), nullable=True),
    sa.Column('preparation_signature_document', sa.Boolean(), nullable=True),
    sa.Column('create_client_signing_link', sa.Boolean(), nullable=True),
    sa.Column('client_signing_link', sa.String(length=500), nullable=True),
    sa.Column('create_attachments_link', sa.Boolean(), nullable=True),
    sa.Column('create_company_seller_link', sa.Boolean(), nullable=True),
    sa.Column('identification_mark', sa.String(length=255), nullable=True),
    sa.Column('action_confirmation_ea', sa.String(length=255), nullable=True),
    sa.Column('ea_registration_status', sa.String(length=255), nullable=True),
    sa.Column('page_spread', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['lead_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_user_id'), 'leads', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_leads_created_by_user_id'), 'leads', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_leads_stage_id'), 'leads', ['stage_id'], unique=False)
    op.create_table('lead_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['lead_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_stage_history_changed_by_user_id'), 'lead_stage_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_lead_stage_history_id'), 'lead_stage_history', ['id'], unique=False)
    op.create_index(op.f('ix_lead_stage_history_lead_id'), 'lead_stage_history', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_stage_history_stage_id'), 'lead_stage_history', ['stage_id'], unique=False)
    # Note: Skipping changes to user_features and audit_logs tables as they're not part of this migration
    
    # Seed default lead stages
    lead_stages_table = sa.table('lead_stages',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('order', sa.Integer),
        sa.column('color', sa.String),
        sa.column('is_default', sa.Boolean),
        sa.column('is_archived', sa.Boolean),
    )
    op.bulk_insert(lead_stages_table, [
        {'id': 1, 'name': 'ליד חדש', 'order': 1, 'color': None, 'is_default': True, 'is_archived': False},
        {'id': 2, 'name': 'מסמכים מוכנים', 'order': 2, 'color': None, 'is_default': False, 'is_archived': False},
        {'id': 3, 'name': 'קישור חתימה נשלח', 'order': 3, 'color': None, 'is_default': False, 'is_archived': False},
        {'id': 4, 'name': 'חתום על ידי לקוח', 'order': 4, 'color': None, 'is_default': False, 'is_archived': False},
        {'id': 5, 'name': 'חתום על ידי פנימי', 'order': 5, 'color': None, 'is_default': False, 'is_archived': False},
        {'id': 6, 'name': 'הושלם', 'order': 6, 'color': None, 'is_default': False, 'is_archived': False},
        {'id': 7, 'name': 'בארכיון', 'order': 7, 'color': None, 'is_default': False, 'is_archived': True},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Skipping changes to user_features and audit_logs tables as they're not part of this migration
    op.drop_index(op.f('ix_lead_stage_history_stage_id'), table_name='lead_stage_history')
    op.drop_index(op.f('ix_lead_stage_history_lead_id'), table_name='lead_stage_history')
    op.drop_index(op.f('ix_lead_stage_history_id'), table_name='lead_stage_history')
    op.drop_index(op.f('ix_lead_stage_history_changed_by_user_id'), table_name='lead_stage_history')
    op.drop_table('lead_stage_history')
    op.drop_index(op.f('ix_leads_stage_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_by_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_user_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_lead_stages_name'), table_name='lead_stages')
    op.drop_index(op.f('ix_lead_stages_id'), table_name='lead_stages')
    op.drop_table('lead_stages')
    # ### end Alembic commands ###

