"""add_document_models

Revision ID: aa6b6b28e12e
Revises: a1b2c3d4e5f6
Create Date: 2026-01-07 10:34:18.699246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6b6b28e12e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rendered_content', sa.Text(), nullable=False),
    sa.Column('pdf_file_path', sa.String(length=1000), nullable=True),
    sa.Column('signing_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, server_default='draft'),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_lead_id'), 'documents', ['lead_id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_template_id'), 'documents', ['template_id'], unique=False)
    op.create_table('document_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('signer_type', sa.String(length=20), nullable=False),
    sa.Column('signer_user_id', sa.Integer(), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=False),
    sa.Column('signer_email', sa.String(length=255), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=False),
    sa.Column('signing_token', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['signer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_signatures_document_id'), 'document_signatures', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_signatures_id'), 'document_signatures', ['id'], unique=False)
    op.create_index(op.f('ix_document_signatures_signing_token'), 'document_signatures', ['signing_token'], unique=False)
    op.create_table('signing_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('signer_type', sa.String(length=20), nullable=False),
    sa.Column('intended_signer_email', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signing_links_document_id'), 'signing_links', ['document_id'], unique=False)
    op.create_index(op.f('ix_signing_links_id'), 'signing_links', ['id'], unique=False)
    op.create_index(op.f('ix_signing_links_token'), 'signing_links', ['token'], unique=True)
    # Note: SQLite doesn't support ALTER COLUMN, so user_features changes are skipped
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signing_links_token'), table_name='signing_links')
    op.drop_index(op.f('ix_signing_links_id'), table_name='signing_links')
    op.drop_index(op.f('ix_signing_links_document_id'), table_name='signing_links')
    op.drop_table('signing_links')
    op.drop_index(op.f('ix_document_signatures_signing_token'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_id'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_document_id'), table_name='document_signatures')
    op.drop_table('document_signatures')
    op.drop_index(op.f('ix_documents_template_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_lead_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###

